// export const WORD_BANK_EN = [
//   "Hollywood",
//   "Well",
//   "Foot",
//   "New York",
//   "Spring",
//   "Court",
//   "Tube",
//   "Point",
//   "Tablet",
//   "Slip",
//   "Date",
//   "Drill",
//   "Lemon",
//   "Bell",
//   "Screen",
//   "Fair",
//   "Torch",
//   "State",
//   "Match",
//   "Iron",
//   "Block",
//   "France",
//   "Australia",
//   "Limousine",
//   "Stream",
//   "Glove",
//   "Nurse",
//   "Leprechaun",
//   "Play",
//   "Tooth",
//   "Arm",
//   "Bermuda",
//   "Diamond",
//   "Whale",
//   "Comic",
//   "Mammoth",
//   "Green",
//   "Pass",
//   "Missile",
//   "Paste",
//   "Drop",
//   "Pheonix",
//   "Marble",
//   "Staff",
//   "Figure",
//   "Park",
//   "Centaur",
//   "Shadow",
//   "Fish",
//   "Cotton",
//   "Egypt",
//   "Theater",
//   "Scale",
//   "Fall",
//   "Track",
//   "Force",
//   "Dinosaur",
//   "Bill",
//   "Mine",
//   "Turkey",
//   "March",
//   "Contract",
//   "Bridge",
//   "Robin",
//   "Line",
//   "Plate",
//   "Band",
//   "Fire",
//   "Bank",
//   "Boom",
//   "Cat",
//   "Shot",
//   "Suit",
//   "Chocolate",
//   "Roulette",
//   "Mercury",
//   "Moon",
//   "Net",
//   "Lawyer",
//   "Satellite",
//   "Angel",
//   "Spider",
//   "Germany",
//   "Fork",
//   "Pitch",
//   "King",
//   "Crane",
//   "Trip",
//   "Dog",
//   "Conductor",
//   "Part",
//   "Bugle",
//   "Witch",
//   "Ketchup",
//   "Press",
//   "Spine",
//   "Worm",
//   "Alps",
//   "Bond",
//   "Pan",
//   "Beijing",
//   "Racket",
//   "Cross",
//   "Seal",
//   "Aztec",
//   "Maple",
//   "Parachute",
//   "Hotel",
//   "Berry",
//   "Soldier",
//   "Ray",
//   "Post",
//   "Greece",
//   "Square",
//   "Mass",
//   "Bat",
//   "Wave",
//   "Car",
//   "Smuggler",
//   "England",
//   "Crash",
//   "Tail",
//   "Card",
//   "Horn",
//   "Capital",
//   "Fence",
//   "Deck",
//   "Buffalo",
//   "Microscope",
//   "Jet",
//   "Duck",
//   "Ring",
//   "Train",
//   "Field",
//   "Gold",
//   "Tick",
//   "Check",
//   "Queen",
//   "Strike",
//   "Kangaroo",
//   "Spike",
//   "Scientist",
//   "Engine",
//   "Shakespeare",
//   "Wind",
//   "Kid",
//   "Embassy",
//   "Robot",
//   "Note",
//   "Ground",
//   "Draft",
//   "Ham",
//   "War",
//   "Mouse",
//   "Center",
//   "Chick",
//   "China",
//   "Bolt",
//   "Spot",
//   "Piano",
//   "Pupil",
//   "Plot",
//   "Lion",
//   "Police",
//   "Head",
//   "Litter",
//   "Concert",
//   "Mug",
//   "Vacuum",
//   "Atlantis",
//   "Straw",
//   "Switch",
//   "Skyscraper",
//   "Laser",
//   "Scuba Diver",
//   "Africa",
//   "Plastic",
//   "Dwarf",
//   "Lap",
//   "Life",
//   "Honey",
//   "Horseshoe",
//   "Unicorn",
//   "Spy",
//   "Pants",
//   "Wall",
//   "Paper",
//   "Sound",
//   "Ice",
//   "Tag",
//   "Web",
//   "Fan",
//   "Orange",
//   "Temple",
//   "Canada",
//   "Scorpion",
//   "Undertaker",
//   "Mail",
//   "Europe",
//   "Soul",
//   "Apple",
//   "Pole",
//   "Tap",
//   "Mouth",
//   "Ambulance",
//   "Dress",
//   "Ice Cream",
//   "Rabbit",
//   "Buck",
//   "Agent",
//   "Sock",
//   "Nut",
//   "Boot",
//   "Ghost",
//   "Oil",
//   "Superhero",
//   "Code",
//   "Kiwi",
//   "Hospital",
//   "Saturn",
//   "Film",
//   "Button",
//   "Snowman",
//   "Helicopter",
//   "Loch Ness",
//   "Log",
//   "Princess",
//   "Time",
//   "Cook",
//   "Revolution",
//   "Shoe",
//   "Mole",
//   "Spell",
//   "Grass",
//   "Washer",
//   "Game",
//   "Beat",
//   "Hole",
//   "Horse",
//   "Pirate",
//   "Link",
//   "Dance",
//   "Fly",
//   "Pit",
//   "Server",
//   "School",
//   "Lock",
//   "Brush",
//   "Pool",
//   "Star",
//   "Jam",
//   "Organ",
//   "Berlin",
//   "Face",
//   "Luck",
//   "Amazon",
//   "Cast",
//   "Gas",
//   "Club",
//   "Sink",
//   "Water",
//   "Chair",
//   "Shark",
//   "Jupiter",
//   "Copper",
//   "Jack",
//   "Platypus",
//   "Stick",
//   "Olive",
//   "Grace",
//   "Bear",
//   "Glass",
//   "Row",
//   "Pistol",
//   "London",
//   "Rock",
//   "Van",
//   "Vet",
//   "Beach",
//   "Charge",
//   "Port",
//   "Disease",
//   "Palm",
//   "Moscow",
//   "Pin",
//   "Washington",
//   "Pyramid",
//   "Opera",
//   "Casino",
//   "Pilot",
//   "String",
//   "Night",
//   "Chest",
//   "Yard",
//   "Teacher",
//   "Pumpkin",
//   "Thief",
//   "Bark",
//   "Bug",
//   "Mint",
//   "Cycle",
//   "Telescope",
//   "Calf",
//   "Air",
//   "Box",
//   "Mount",
//   "Thumb",
//   "Antarctica",
//   "Trunk",
//   "Snow",
//   "Penguin",
//   "Root",
//   "Bar",
//   "File",
//   "Hawk",
//   "Battery",
//   "Compound",
//   "Slug",
//   "Octopus",
//   "Whip",
//   "America",
//   "Ivory",
//   "Pound",
//   "Sub",
//   "Cliff",
//   "Lab",
//   "Eagle",
//   "Genius",
//   "Ship",
//   "Dice",
//   "Hood",
//   "Heart",
//   "Novel",
//   "Pipe",
//   "Himalayas",
//   "Crown",
//   "Round",
//   "India",
//   "Needle",
//   "Shop",
//   "Watch",
//   "Lead",
//   "Tie",
//   "Table",
//   "Cell",
//   "Cover",
//   "Czech",
//   "Back",
//   "Bomb",
//   "Ruler",
//   "Forest",
//   "Bottle",
//   "Space",
//   "Hook",
//   "Doctor",
//   "Ball",
//   "Bow",
//   "Degree",
//   "Rome",
//   "Plane",
//   "Giant",
//   "Nail",
//   "Dragon",
//   "Stadium",
//   "Flute",
//   "Carrot",
//   "Wake",
//   "Fighter",
//   "Model",
//   "Tokyo",
//   "Eye",
//   "Mexico",
//   "Hand",
//   "Swing",
//   "Key",
//   "Alien",
//   "Tower",
//   "Poison",
//   "Cricket",
//   "Cold",
//   "Knife",
//   "Church",
//   "Board",
//   "Cloak",
//   "Ninja",
//   "Olympus",
//   "Belt",
//   "Light",
//   "Death",
//   "Stock",
//   "Millionaire",
//   "Day",
//   "Knight",
//   "Pie",
//   "Bed",
//   "Circle",
//   "Rose",
//   "Change",
//   "Cap",
//   "Triangle",
// ];

// export const WORD_BANK_TR = [
//   "Hollywood",
//   "Kuyu",
//   "Ayak",
//   "New York",
//   "Bahar",
//   "Mahkeme",
//   "Tüp",
//   "Nokta",
//   "Tablet",
//   "Kayma",
//   "Tarih",
//   "Delmek",
//   "Limon",
//   "Zil",
//   "Ekran",
//   "Adil",
//   "Meşale",
//   "Durum",
//   "Kibrit",
//   "Ütü",
//   "Engellemek",
//   "Fransa",
//   "Avustralya",
//   "Limuzin",
//   "Aktarım",
//   "Eldiven",
//   "Hemşire",
//   "Cüce cin",
//   "Oynamak",
//   "Diş",
//   "Kol",
//   "Bermuda",
//   "Elmas",
//   "Balina",
//   "Komik",
//   "Mamut",
//   "Yeşil",
//   "Geçmek",
//   "Füze",
//   "Yapıştırmak",
//   "Düşürmek",
//   "Phoenix",
//   "Mermer",
//   "Kadro",
//   "Figür",
//   "Park",
//   "Sentor",
//   "Gölge",
//   "Balık",
//   "Pamuk",
//   "Mısır",
//   "Tiyatro",
//   "Ölçek",
//   "Düşmek",
//   "İzlemek",
//   "Güç",
//   "Dinozor",
//   "Fatura",
//   "Bana ait",
//   "Hindi",
//   "Mart",
//   "Sözleşme",
//   "Köprü",
//   "Robin",
//   "Astar",
//   "Plaka",
//   "Bant",
//   "Ateş",
//   "Banka",
//   "Boom",
//   "Kedi",
//   "Atış",
//   "Uygun olmak",
//   "Çikolata",
//   "Rulet",
//   "Merkür",
//   "Ay",
//   "Açık",
//   "Avukat",
//   "Uydu",
//   "Melek",
//   "Örümcek",
//   "Almanya",
//   "Çatal",
//   "Saha",
//   "Kral",
//   "Vinç",
//   "Seyahat",
//   "Köpek",
//   "Kondüktör",
//   "Parça",
//   "Boru",
//   "Cadı",
//   "Ketçap",
//   "Basmak",
//   "Omurga",
//   "Solucan",
//   "Alpler",
//   "Bağlamak",
//   "Tava",
//   "Pekin",
//   "Raket",
//   "Geçmek",
//   "Fok",
//   "Aztek",
//   "Akçaağaç",
//   "Paraşüt",
//   "Otel",
//   "Meyve",
//   "Asker",
//   "Işın",
//   "Postalamak",
//   "Yunanistan",
//   "Kare",
//   "Yığın",
//   "Yarasa",
//   "Dalga",
//   "Araba",
//   "Kaçakçı",
//   "İngiltere",
//   "Kaza",
//   "Kuyruk",
//   "Kart",
//   "Korna",
//   "Başkent",
//   "Çit",
//   "Güverte",
//   "Bufalo",
//   "Mikroskop",
//   "Jet",
//   "Ördek",
//   "Yüzük",
//   "Tren",
//   "Alan",
//   "Altın",
//   "Tık",
//   "Kontrol etmek",
//   "Kraliçe",
//   "Çarpmak",
//   "Kanguru",
//   "Başak",
//   "Bilim adamı",
//   "Motor",
//   "Shakespeare",
//   "Rüzgâr",
//   "Çocuk",
//   "Elçilik",
//   "Robot",
//   "Not",
//   "Zemin",
//   "Taslak",
//   "Jambon",
//   "Savaş",
//   "Fare",
//   "Merkez",
//   "civciv",
//   "Çin",
//   "Cıvata",
//   "Leke",
//   "Piyano",
//   "Öğrenci",
//   "Komplo",
//   "Aslan",
//   "Polis",
//   "KAFA",
//   "Yavrulamak",
//   "Konser",
//   "Saldırıp soymak",
//   "Vakum",
//   "Atlantis",
//   "Pipet",
//   "Anahtar",
//   "Gökdelen",
//   "Lazer",
//   "Tüplü dalış",
//   "Afrika",
//   "Plastik",
//   "Cüce",
//   "Kucak",
//   "Hayat",
//   "Bal",
//   "At nalı",
//   "Tek boynuzlu at",
//   "Casus",
//   "Pantolon",
//   "Duvar",
//   "Kağıt",
//   "Ses",
//   "Buz",
//   "Etiket",
//   "Ağ",
//   "Fan",
//   "Turuncu",
//   "Tapınak",
//   "Kanada",
//   "Akrep",
//   "Cenazeci",
//   "Posta",
//   "Avrupa",
//   "Ruh",
//   "Elma",
//   "Kutup",
//   "Musluk",
//   "Ağız",
//   "Ambulans",
//   "Elbise",
//   "Dondurma",
//   "Tavşan",
//   "Buck",
//   "Ajan",
//   "Çorap",
//   "Ceviz",
//   "Bot",
//   "Hayalet",
//   "Yağ",
//   "Süper kahraman",
//   "Kod",
//   "Kivi",
//   "Hastane",
//   "Satürn",
//   "Film",
//   "Düğme",
//   "Kardan adam",
//   "Helikopter",
//   "Loch Ness",
//   "Kayıt",
//   "Prenses",
//   "Zaman",
//   "Aşçı",
//   "Devrim",
//   "Ayakkabı",
//   "Köstebek",
//   "Hecelemek",
//   "Çimen",
//   "Yıkama makinesi",
//   "Oyun",
//   "Vurmak",
//   "Delik",
//   "Atış",
//   "Korsan",
//   "Bağlantı",
//   "Dans",
//   "Uçmak",
//   "Çukur",
//   "Sunucu",
//   "Okul",
//   "Kilit",
//   "Fırçalamak",
//   "Havuz",
//   "Yıldız",
//   "Reçel",
//   "Organ",
//   "Berlin",
//   "Yüz",
//   "Şans",
//   "Amazon",
//   "Döküm",
//   "Gaz",
//   "Kulüp",
//   "Atmak",
//   "Su",
//   "Sandalye",
//   "Köpek balığı",
//   "Jüpiter",
//   "Bakır",
//   "Jack",
//   "Ornitorenk",
//   "Sopa",
//   "Zeytin",
//   "Lütuf",
//   "Ayı",
//   "Bardak",
//   "Sıra",
//   "Tabanca",
//   "Londra",
//   "Kaynak",
//   "Kamyonet",
//   "Veteriner",
//   "Sahil",
//   "Şarj",
//   "Liman",
//   "Hastalık",
//   "Avuç içi",
//   "Moskova",
//   "Toplu iğne",
//   "Washington",
//   "Piramit",
//   "Opera",
//   "Kumarhane",
//   "Pilot",
//   "Sicim",
//   "Gece",
//   "Göğüs",
//   "Bahçe",
//   "Öğretmen",
//   "Kabak",
//   "Hırsız",
//   "Havlamak",
//   "Böcek",
//   "Nane",
//   "Döngü",
//   "Teleskop",
//   "Buzağı",
//   "Hava",
//   "Kutu",
//   "Dağ",
//   "Baş parmak",
//   "Antarktika",
//   "Gövde",
//   "Kar",
//   "Penguen",
//   "Kök",
//   "Çubuk",
//   "Dosya",
//   "Şahin",
//   "Pil",
//   "Birleştirmek",
//   "Sümüklüböcek",
//   "Ahtapot",
//   "Kırbaç",
//   "Amerika",
//   "Fildişi",
//   "Pound",
//   "Alt",
//   "Uçurum",
//   "Laboratuvar",
//   "Kartal",
//   "Dahi",
//   "Gemi",
//   "Zar",
//   "Kapüşon",
//   "Kalp",
//   "Roman",
//   "Boru",
//   "Himalayalar",
//   "Taç",
//   "Yuvarlak",
//   "Hindistan",
//   "İğne",
//   "Mağaza",
//   "Kol saati",
//   "Yol göstermek",
//   "Bağlamak",
//   "Masa",
//   "Hücre",
//   "Kapak",
//   "Çek",
//   "Geri",
//   "Bomba",
//   "Cetvel",
//   "Orman",
//   "Şişe",
//   "Uzay",
//   "Kanca",
//   "Doktor",
//   "Top",
//   "Yay",
//   "Derece",
//   "Roma",
//   "Uçak",
//   "Devasa",
//   "Çivi",
//   "Ejderha",
//   "Stadyum",
//   "Flüt",
//   "Havuç",
//   "Uyanmak",
//   "Savaşçı",
//   "Model",
//   "Tokyo",
//   "Göz",
//   "Meksika",
//   "El",
//   "Sallanmak",
//   "Anahtar",
//   "Yabancı",
//   "Kule",
//   "Zehir",
//   "Kriket",
//   "Soğuk",
//   "Bıçak",
//   "Kilise",
//   "Pano",
//   "Pelerin",
//   "Ninja",
//   "Olimpos",
//   "Kemer",
//   "Işık",
//   "Ölüm",
//   "Stoklamak",
//   "Milyoner",
//   "Gün",
//   "Şövalye",
//   "Turta",
//   "Yatak",
//   "Daire",
//   "Gül",
//   "Değiştirmek",
//   "Şapka",
//   "Üçgen",
// ];

// export const WORD_BANK_CZE = [
//   "Hollywood",
//   "Studna",
//   "Chodidlo",
//   "New York",
//   "Jaro",
//   "Soud",
//   "Trubka",
//   "Bod",
//   "Tableta",
//   "Uklouznutí",
//   "Datum",
//   "Vrtat",
//   "Citrón",
//   "Zvonek",
//   "Obrazovka",
//   "Veletrh",
//   "Pochodeň",
//   "Stát",
//   "Zápas",
//   "Žehlička",
//   "Blok",
//   "Francie",
//   "Austrálie",
//   "Limuzína",
//   "Proud",
//   "Rukavice",
//   "Sestřička",
//   "Skřítek",
//   "Hrát si",
//   "Zub",
//   "Paže",
//   "Bermudy",
//   "Diamant",
//   "Velryba",
//   "Komik",
//   "Mamut",
//   "Zelená",
//   "Složit",
//   "Střela",
//   "Vložit",
//   "Upustit",
//   "Pheonix",
//   "Mramor",
//   "Personál",
//   "Postava",
//   "Park",
//   "Kentaur",
//   "Stín",
//   "Ryba",
//   "Bavlna",
//   "Egypt",
//   "Divadlo",
//   "Měřítko",
//   "Podzim",
//   "Dráha",
//   "Platnost",
//   "Dinosaurus",
//   "Účtovat",
//   "Těžit",
//   "Krocan",
//   "Březen",
//   "Smlouva",
//   "Most",
//   "Červenka",
//   "Čára",
//   "Talíř",
//   "Kapela",
//   "Oheň",
//   "Banka",
//   "Boom",
//   "Kočka",
//   "Výstřel",
//   "Oblek",
//   "Čokoláda",
//   "Ruleta",
//   "Rtuť",
//   "Měsíc",
//   "Síť",
//   "Právník",
//   "Družice",
//   "Anděl",
//   "Pavouk",
//   "Německo",
//   "Vidlička",
//   "Rozteč",
//   "Král",
//   "Jeřáb",
//   "Výlet",
//   "Pes",
//   "Dirigent",
//   "Část",
//   "Polnice",
//   "Čarodějnice",
//   "Kečup",
//   "Lis",
//   "Páteř",
//   "Červ",
//   "Alpy",
//   "Pouto",
//   "Pánev",
//   "Peking",
//   "Raketa",
//   "Přejít",
//   "Těsnění",
//   "Azték",
//   "Javor",
//   "Padák",
//   "Hotel",
//   "Bobule",
//   "Voják",
//   "Paprsek",
//   "Pošta",
//   "Řecko",
//   "Náměstí",
//   "Hmotnost",
//   "Netopýr",
//   "Mávat",
//   "Auto",
//   "Pašerák",
//   "Anglie",
//   "Pád",
//   "Ocas",
//   "Karta",
//   "Roh",
//   "Hlavní město",
//   "Plot",
//   "Paluba",
//   "Buvol",
//   "Mikroskop",
//   "Proud",
//   "Kachna",
//   "Prsten",
//   "Vlak",
//   "Pole",
//   "Zlato",
//   "Klíště",
//   "Šek",
//   "Královna",
//   "Stávkovat",
//   "Klokan",
//   "Špice",
//   "Vědec",
//   "Motor",
//   "Shakespeare",
//   "Vítr",
//   "Dítě",
//   "Ambasáda",
//   "Robot",
//   "Poznámka",
//   "Přízemní",
//   "Návrh",
//   "Šunka",
//   "Válka",
//   "Myš",
//   "Centrum",
//   "Kuřátko",
//   "Čína",
//   "Šroub",
//   "Bod",
//   "Klavír",
//   "Žák",
//   "Spiknutí",
//   "Lev",
//   "Policie",
//   "Hlava",
//   "Smetí",
//   "Koncert",
//   "Džbánek",
//   "Vakuum",
//   "Atlantis",
//   "Sláma",
//   "Přepínač",
//   "Mrakodrap",
//   "Laser",
//   "Potápěč",
//   "Afrika",
//   "Plastický",
//   "Trpaslík",
//   "Klín",
//   "Život",
//   "Miláček",
//   "Podkova",
//   "Jednorožec",
//   "Vyzvědač",
//   "Kalhoty",
//   "Zeď",
//   "Papír",
//   "Zvuk",
//   "Led",
//   "Štítek",
//   "Web",
//   "Fanoušek",
//   "Oranžový",
//   "Chrám",
//   "Kanada",
//   "Štír",
//   "Hrobař",
//   "Pošta",
//   "Evropa",
//   "Duše",
//   "Jablko",
//   "Pól",
//   "Kohoutek",
//   "Pusa",
//   "Záchranář",
//   "Šaty",
//   "Zmrzlina",
//   "Králičí",
//   "Dolar",
//   "Činidlo",
//   "Ponožka",
//   "Matice",
//   "Boot",
//   "Duch",
//   "Olej",
//   "Superhrdina",
//   "Kód",
//   "Kiwi",
//   "Nemocnice",
//   "Saturn",
//   "Film",
//   "Knoflík",
//   "Sněhulák",
//   "Helikoptéra",
//   "Loch Ness",
//   "Log",
//   "Princezna",
//   "Čas",
//   "Kuchař",
//   "Revoluce",
//   "Boty",
//   "Krtek",
//   "Hláskovat",
//   "Tráva",
//   "Podložka",
//   "Hra",
//   "Porazit",
//   "Otvor",
//   "Kůň",
//   "Pirát",
//   "Odkaz",
//   "Tanec",
//   "Létat",
//   "Jáma",
//   "Server",
//   "Škola",
//   "Zámek",
//   "Štětec",
//   "Bazén",
//   "Hvězda",
//   "Džem",
//   "Orgán",
//   "Berlín",
//   "Tvář",
//   "Štěstí",
//   "Amazonka",
//   "Obsazení",
//   "Plyn",
//   "Klub",
//   "Dřez",
//   "Voda",
//   "Židle",
//   "Žralok",
//   "Jupiter",
//   "Měď",
//   "Zvedák",
//   "Ptakopysk",
//   "Lepit",
//   "Olivový",
//   "Milost",
//   "Medvěd",
//   "Sklenka",
//   "Řádek",
//   "Pistole",
//   "Londýn",
//   "Skála",
//   "Dodávka",
//   "Vet",
//   "Pláž",
//   "Nabít",
//   "Přístav",
//   "Choroba",
//   "Dlaň",
//   "Moskva",
//   "Kolík",
//   "Washington",
//   "Pyramida",
//   "Opera",
//   "Kasino",
//   "Pilot",
//   "Tětiva",
//   "Noc",
//   "Hruď",
//   "Yard",
//   "Učitel",
//   "Dýně",
//   "Zloděj",
//   "Kůra",
//   "Chyba",
//   "Máta",
//   "Cyklus",
//   "Dalekohled",
//   "Tele",
//   "Vzduch",
//   "Krabice",
//   "Mount",
//   "Palec",
//   "Antarktida",
//   "Kmen",
//   "Sníh",
//   "Tučňák",
//   "Vykořenit",
//   "Bar",
//   "Soubor",
//   "Jestřáb",
//   "Baterie",
//   "Sloučenina",
//   "Slimák",
//   "Chobotnice",
//   "Bič",
//   "Amerika",
//   "Slonová kost",
//   "Libra",
//   "Sub",
//   "Útes",
//   "Laboratoř",
//   "Orel",
//   "Génius",
//   "Loď",
//   "Kostky",
//   "Kapuce",
//   "Srdce",
//   "Román",
//   "Trubka",
//   "Himaláje",
//   "Koruna",
//   "Kolo",
//   "Indie",
//   "Jehla",
//   "Prodejna",
//   "Hodinky",
//   "Vést",
//   "Kravata",
//   "Stůl",
//   "Buňka",
//   "Pokrýt",
//   "Čeština",
//   "Zadní",
//   "Bombardovat",
//   "Pravítko",
//   "Les",
//   "Láhev",
//   "Prostor",
//   "Háček",
//   "Doktor",
//   "Míč",
//   "Luk",
//   "Stupeň",
//   "Řím",
//   "Letadlo",
//   "Obří",
//   "Nehet",
//   "Drak",
//   "Stadión",
//   "Flétna",
//   "Mrkev",
//   "Probudit",
//   "Bojovník",
//   "Modelka",
//   "Tokio",
//   "Oko",
//   "Mexiko",
//   "Ruka",
//   "Houpačka",
//   "Klíč",
//   "Mimozemšťan",
//   "Věž",
//   "Jed",
//   "Kriket",
//   "Studený",
//   "Nůž",
//   "Kostel",
//   "Prkno",
//   "Plášť",
//   "Ninja",
//   "Olympus",
//   "Pás",
//   "Světlo",
//   "Smrt",
//   "Skladem",
//   "Milionář",
//   "Den",
//   "Rytíř",
//   "Koláč",
//   "Postel",
//   "Kruh",
//   "Růže",
//   "Změna",
//   "Víčko",
//   "Trojúhelník",
// ];

export const WORD_BANK = [
  {
    default: "Hollywood",
    english: "Hollywood",
    turkish: "Hollywood",
    czech: "Hollywood",
  },
  {
    default: "Well",
    english: "Well",
    turkish: "Kuyu",
    czech: "Studna",
  },
  {
    default: "Foot",
    english: "Foot",
    turkish: "Ayak",
    czech: "Noha",
  },
  {
    default: "New York",
    english: "New York",
    turkish: "New York",
    czech: "New York",
  },
  {
    default: "Spring",
    english: "Spring",
    turkish: "Bahar",
    czech: "Jaro",
  },
  {
    default: "Court",
    english: "Court",
    turkish: "Mahkeme",
    czech: "Soud",
  },
  {
    default: "Tube",
    english: "Tube",
    turkish: "Tüp",
    czech: "Trubka",
  },
  {
    default: "Point",
    english: "Point",
    turkish: "Nokta",
    czech: "Bod",
  },
  {
    default: "Tablet",
    english: "Tablet",
    turkish: "Tablet",
    czech: "Tableta",
  },
  {
    default: "Slip",
    english: "Slip",
    turkish: "Kayma",
    czech: "Uklouznut",
  },
  {
    default: "Date",
    english: "Date",
    turkish: "Tarih",
    czech: "Datum",
  },
  {
    default: "Drill",
    english: "Drill",
    turkish: "Delmek",
    czech: "Vrtat",
  },
  {
    default: "Lemon",
    english: "Lemon",
    turkish: "Limon",
    czech: "Citrón",
  },
  {
    default: "Bell",
    english: "Bell",
    turkish: "Zil",
    czech: "Zvonek",
  },
  {
    default: "Screen",
    english: "Screen",
    turkish: "Ekran",
    czech: "Obrazovka",
  },
  {
    default: "Fair",
    english: "Fair",
    turkish: "Adil",
    czech: "Veletrh",
  },
  {
    default: "Torch",
    english: "Torch",
    turkish: "Meşale",
    czech: "Pochodeň",
  },
  {
    default: "State",
    english: "State",
    turkish: "Ülke",
    czech: "Stát",
  },
  {
    default: "Match",
    english: "Match",
    turkish: "Kibrit",
    czech: "Zápalka",
  },
  {
    default: "Iron",
    english: "Iron",
    turkish: "Ütü",
    czech: "Žehlička",
  },
  {
    default: "Block",
    english: "Block",
    turkish: "Blok",
    czech: "Blok",
  },
  {
    default: "France",
    english: "France",
    turkish: "Fransa",
    czech: "Francie",
  },
  {
    default: "Australia",
    english: "Australia",
    turkish: "Avustralya",
    czech: "Austrálie",
  },
  {
    default: "Limousine",
    english: "Limousine",
    turkish: "Limuzin",
    czech: "Limuzína",
  },
  {
    default: "Stream",
    english: "Stream",
    turkish: "Akarsu",
    czech: "Proud",
  },
  {
    default: "Glove",
    english: "Glove",
    turkish: "Eldiven",
    czech: "Rukavice",
  },
  {
    default: "Nurse",
    english: "Nurse",
    turkish: "Hemşire",
    czech: "Sestřička",
  },
  {
    default: "Leprechaun",
    english: "Leprechaun",
    turkish: "Cüce cin",
    czech: "Skřítek",
  },
  {
    default: "Play",
    english: "Play",
    turkish: "Oynamak",
    czech: "Hrát",
  },
  {
    default: "Tooth",
    english: "Tooth",
    turkish: "Diş",
    czech: "Zub",
  },
  {
    default: "Arm",
    english: "Arm",
    turkish: "Kol",
    czech: "Ruka",
  },
  {
    default: "Diamond",
    english: "Diamond",
    turkish: "Elmas",
    czech: "Diamant",
  },
  {
    default: "Whale",
    english: "Whale",
    turkish: "Balina",
    czech: "Velryba",
  },
  {
    default: "Comic",
    english: "Comic",
    turkish: "Komedi",
    czech: "Komedie",
  },
  {
    default: "Mammoth",
    english: "Mammoth",
    turkish: "Mamut",
    czech: "Mamut",
  },
  {
    default: "Green",
    english: "Green",
    turkish: "Yeşil",
    czech: "Zelená",
  },
  {
    default: "Pass",
    english: "Pass",
    turkish: "Geçmek",
    czech: "Složit",
  },
  {
    default: "Missile",
    english: "Missile",
    turkish: "Füze",
    czech: "Raketa",
  },
  {
    default: "Paste",
    english: "Paste",
    turkish: "Yapıştırmak",
    czech: "Vložit",
  },
  {
    default: "Drop",
    english: "Drop",
    turkish: "Düşürmek",
    czech: "Upustit",
  },
  {
    default: "Pheonix",
    english: "Pheonix",
    turkish: "Anka kuşu",
    czech: "Pheonix",
  },
  {
    default: "Marble",
    english: "Marble",
    turkish: "Mermer",
    czech: "Mramor",
  },
  {
    default: "Staff",
    english: "Staff",
    turkish: "Kadro",
    czech: "Personál",
  },
  {
    default: "Figure",
    english: "Figure",
    turkish: "Figür",
    czech: "Postava",
  },
  {
    default: "Park",
    english: "Park",
    turkish: "Park",
    czech: "Park",
  },
  {
    default: "Centaur",
    english: "Centaur",
    turkish: "Sentor",
    czech: "Kentaur",
  },
  {
    default: "Shadow",
    english: "Shadow",
    turkish: "Gölge",
    czech: "Stín",
  },
  {
    default: "Fish",
    english: "Fish",
    turkish: "Balık",
    czech: "Ryba",
  },
  {
    default: "Cotton",
    english: "Cotton",
    turkish: "Pamuk",
    czech: "Bavlna",
  },
  {
    default: "Egypt",
    english: "Egypt",
    turkish: "Mısır",
    czech: "Egypt",
  },
  {
    default: "Theater",
    english: "Theater",
    turkish: "Tiyatro",
    czech: "Divadlo",
  },
  {
    default: "Scale",
    english: "Scale",
    turkish: "Ölçek",
    czech: "Měřítko",
  },
  {
    default: "Fall",
    english: "Fall",
    turkish: "Sonbahar",
    czech: "Podzim",
  },
  {
    default: "Track",
    english: "Track",
    turkish: "Pist",
    czech: "Dráha",
  },
  {
    default: "Force",
    english: "Force",
    turkish: "Güç",
    czech: "Síla",
  },
  {
    default: "Dinosaur",
    english: "Dinosaur",
    turkish: "Dinozor",
    czech: "Dinosaurus",
  },
  {
    default: "Bill",
    english: "Bill",
    turkish: "Fatura",
    czech: "Faktura",
  },
  {
    default: "Mine",
    english: "Mine",
    turkish: "Maden",
    czech: "Důl",
  },
  {
    default: "Turkey",
    english: "Turkey",
    turkish: "Hindi",
    czech: "Krocan",
  },
  {
    default: "March",
    english: "March",
    turkish: "Mart",
    czech: "Březen",
  },
  {
    default: "Contract",
    english: "Contract",
    turkish: "Sözleşme",
    czech: "Smlouva",
  },
  {
    default: "Bridge",
    english: "Bridge",
    turkish: "Köprü",
    czech: "Most",
  },
  {
    default: "Line",
    english: "Line",
    turkish: "Astar",
    czech: "Čára",
  },
  {
    default: "Plate",
    english: "Plate",
    turkish: "Tabak",
    czech: "Talíř",
  },
  {
    default: "Band",
    english: "Band",
    turkish: "Bant",
    czech: "Náplast",
  },
  {
    default: "Fire",
    english: "Fire",
    turkish: "Ateş",
    czech: "Oheň",
  },
  {
    default: "Bank",
    english: "Bank",
    turkish: "Banka",
    czech: "Banka",
  },
  {
    default: "Boom",
    english: "Boom",
    turkish: "Boom",
    czech: "Boom",
  },
  {
    default: "Cat",
    english: "Cat",
    turkish: "Kedi",
    czech: "Kočka",
  },
  {
    default: "Shot",
    english: "Shot",
    turkish: "Atış",
    czech: "Výstřel",
  },
  {
    default: "Suit",
    english: "Suit",
    turkish: "Takım",
    czech: "Oblek",
  },
  {
    default: "Chocolate",
    english: "Chocolate",
    turkish: "Çikolata",
    czech: "Čokoláda",
  },
  {
    default: "Roulette",
    english: "Roulette",
    turkish: "Rulet",
    czech: "Ruleta",
  },
  {
    default: "Mercury",
    english: "Mercury",
    turkish: "Merkür",
    czech: "Merkur",
  },
  {
    default: "Moon",
    english: "Moon",
    turkish: "Ay",
    czech: "Měsíc",
  },
  {
    default: "Net",
    english: "Net",
    turkish: "Ağ",
    czech: "Síť",
  },
  {
    default: "Lawyer",
    english: "Lawyer",
    turkish: "Avukat",
    czech: "Právník",
  },
  {
    default: "Satellite",
    english: "Satellite",
    turkish: "Uydu",
    czech: "Satelit",
  },
  {
    default: "Angel",
    english: "Angel",
    turkish: "Melek",
    czech: "Anděl",
  },
  {
    default: "Spider",
    english: "Spider",
    turkish: "Örümcek",
    czech: "Pavouk",
  },
  {
    default: "Germany",
    english: "Germany",
    turkish: "Almanya",
    czech: "Německo",
  },
  {
    default: "Fork",
    english: "Fork",
    turkish: "Çatal",
    czech: "Vidlička",
  },
  {
    default: "King",
    english: "King",
    turkish: "Kral",
    czech: "Král",
  },
  {
    default: "Crane",
    english: "Crane",
    turkish: "Vinç",
    czech: "Jeřáb",
  },
  {
    default: "Trip",
    english: "Trip",
    turkish: "Seyahat",
    czech: "Výlet",
  },
  {
    default: "Dog",
    english: "Dog",
    turkish: "Köpek",
    czech: "Pes",
  },
  {
    default: "Conductor",
    english: "Conductor",
    turkish: "Kondüktör",
    czech: "Dirigent",
  },
  {
    default: "Part",
    english: "Part",
    turkish: "Parça",
    czech: "Část",
  },
  {
    default: "Witch",
    english: "Witch",
    turkish: "Cadı",
    czech: "Čarodějnice",
  },
  {
    default: "Ketchup",
    english: "Ketchup",
    turkish: "Ketçap",
    czech: "Kečup",
  },
  {
    default: "Press",
    english: "Press",
    turkish: "Basmak",
    czech: "Tlak",
  },
  {
    default: "Spine",
    english: "Spine",
    turkish: "Omurga",
    czech: "Páteř",
  },
  {
    default: "Worm",
    english: "Worm",
    turkish: "Solucan",
    czech: "Červ",
  },
  {
    default: "Alps",
    english: "Alps",
    turkish: "Alpler",
    czech: "Alpy",
  },
  {
    default: "Bond",
    english: "Bond",
    turkish: "Bağ",
    czech: "Pouto",
  },
  {
    default: "Pan",
    english: "Pan",
    turkish: "Tava",
    czech: "Pánev",
  },
  {
    default: "Beijing",
    english: "Beijing",
    turkish: "Pekin",
    czech: "Peking",
  },
  {
    default: "Racket",
    english: "Racket",
    turkish: "Raket",
    czech: "Raketa",
  },
  {
    default: "Cross",
    english: "Cross",
    turkish: "Geçmek",
    czech: "Přejít",
  },
  {
    default: "Seal",
    english: "Seal",
    turkish: "Fok",
    czech: "Tuleň",
  },
  {
    default: "Aztec",
    english: "Aztec",
    turkish: "Aztek",
    czech: "Azték",
  },
  {
    default: "Maple",
    english: "Maple",
    turkish: "Akçaağaç",
    czech: "Javor",
  },
  {
    default: "Parachute",
    english: "Parachute",
    turkish: "Paraşüt",
    czech: "Padák",
  },
  {
    default: "Hotel",
    english: "Hotel",
    turkish: "Otel",
    czech: "Hotel",
  },
  {
    default: "Berry",
    english: "Berry",
    turkish: "Meyve",
    czech: "Bobule",
  },
  {
    default: "Soldier",
    english: "Soldier",
    turkish: "Asker",
    czech: "Voják",
  },
  {
    default: "Ray",
    english: "Ray",
    turkish: "Işın",
    czech: "Paprsek",
  },
  {
    default: "Post",
    english: "Post",
    turkish: "Posta",
    czech: "Pošta",
  },
  {
    default: "Greece",
    english: "Greece",
    turkish: "Yunanistan",
    czech: "Řecko",
  },
  {
    default: "Square",
    english: "Square",
    turkish: "Kare",
    czech: "Čtverec",
  },
  {
    default: "Mass",
    english: "Mass",
    turkish: "Yığın",
    czech: "Hmotnost",
  },
  {
    default: "Bat",
    english: "Bat",
    turkish: "Yarasa",
    czech: "Netopýr",
  },
  {
    default: "Wave",
    english: "Wave",
    turkish: "Dalga",
    czech: "Vlna",
  },
  {
    default: "Car",
    english: "Car",
    turkish: "Araba",
    czech: "Auto",
  },
  {
    default: "Smuggler",
    english: "Smuggler",
    turkish: "Kaçakçı",
    czech: "Pašerák",
  },
  {
    default: "England",
    english: "England",
    turkish: "İngiltere",
    czech: "Anglie",
  },
  {
    default: "Crash",
    english: "Crash",
    turkish: "Kaza",
    czech: "Náraz",
  },
  {
    default: "Tail",
    english: "Tail",
    turkish: "Kuyruk",
    czech: "Ocas",
  },
  {
    default: "Card",
    english: "Card",
    turkish: "Kart",
    czech: "Karta",
  },
  {
    default: "Horn",
    english: "Horn",
    turkish: "Boynuz",
    czech: "Roh",
  },
  {
    default: "Capital",
    english: "Capital",
    turkish: "Başkent",
    czech: "Hlavní město",
  },
  {
    default: "Fence",
    english: "Fence",
    turkish: "Çit",
    czech: "Plot",
  },
  {
    default: "Deck",
    english: "Deck",
    turkish: "Güverte",
    czech: "Paluba",
  },
  {
    default: "Buffalo",
    english: "Buffalo",
    turkish: "Bufalo",
    czech: "Buvol",
  },
  {
    default: "Microscope",
    english: "Microscope",
    turkish: "Mikroskop",
    czech: "Mikroskop",
  },
  {
    default: "Jet",
    english: "Jet",
    turkish: "Jet",
    czech: "Stíhačka",
  },
  {
    default: "Duck",
    english: "Duck",
    turkish: "Ördek",
    czech: "Kachna",
  },
  {
    default: "Ring",
    english: "Ring",
    turkish: "Yüzük",
    czech: "Prsten",
  },
  {
    default: "Train",
    english: "Train",
    turkish: "Tren",
    czech: "Vlak",
  },
  {
    default: "Field",
    english: "Field",
    turkish: "Alan",
    czech: "Pole",
  },
  {
    default: "Gold",
    english: "Gold",
    turkish: "Altın",
    czech: "Zlato",
  },
  {
    default: "Tick",
    english: "Tick",
    turkish: "Kene",
    czech: "Klíště",
  },
  {
    default: "Check",
    english: "Check",
    turkish: "Çek",
    czech: "Šek",
  },
  {
    default: "Queen",
    english: "Queen",
    turkish: "Kraliçe",
    czech: "Královna",
  },
  {
    default: "Strike",
    english: "Strike",
    turkish: "Çarpmak",
    czech: "Udeřit",
  },
  {
    default: "Kangaroo",
    english: "Kangaroo",
    turkish: "Kanguru",
    czech: "Klokan",
  },
  {
    default: "Spike",
    english: "Spike",
    turkish: "Sivri",
    czech: "Špice",
  },
  {
    default: "Scientist",
    english: "Scientist",
    turkish: "Bilim adamı",
    czech: "Vědec",
  },
  {
    default: "Engine",
    english: "Engine",
    turkish: "Motor",
    czech: "Motor",
  },
  {
    default: "Shakespeare",
    english: "Shakespeare",
    turkish: "Shakespeare",
    czech: "Shakespeare",
  },
  {
    default: "Wind",
    english: "Wind",
    turkish: "Rüzgâr",
    czech: "Vítr",
  },
  {
    default: "Kid",
    english: "Kid",
    turkish: "Çocuk",
    czech: "Dítě",
  },
  {
    default: "Embassy",
    english: "Embassy",
    turkish: "Elçilik",
    czech: "Ambasáda",
  },
  {
    default: "Robot",
    english: "Robot",
    turkish: "Robot",
    czech: "Robot",
  },
  {
    default: "Note",
    english: "Note",
    turkish: "Not",
    czech: "Poznámka",
  },
  {
    default: "Ground",
    english: "Ground",
    turkish: "Zemin",
    czech: "Přízemní",
  },
  {
    default: "Draft",
    english: "Draft",
    turkish: "Taslak",
    czech: "Návrh",
  },
  {
    default: "Ham",
    english: "Ham",
    turkish: "Jambon",
    czech: "Šunka",
  },
  {
    default: "War",
    english: "War",
    turkish: "Savaş",
    czech: "Válka",
  },
  {
    default: "Mouse",
    english: "Mouse",
    turkish: "Fare",
    czech: "Myš",
  },
  {
    default: "Center",
    english: "Center",
    turkish: "Merkez",
    czech: "Centrum",
  },
  {
    default: "Chick",
    english: "Chick",
    turkish: "Civciv",
    czech: "Kuřátko",
  },
  {
    default: "China",
    english: "China",
    turkish: "Çin",
    czech: "Čína",
  },
  {
    default: "Bolt",
    english: "Bolt",
    turkish: "Cıvata",
    czech: "Šroub",
  },
  {
    default: "Spot",
    english: "Spot",
    turkish: "Leke",
    czech: "Skvrna",
  },
  {
    default: "Piano",
    english: "Piano",
    turkish: "Piyano",
    czech: "Klavír",
  },
  {
    default: "Student",
    english: "Student",
    turkish: "Öğrenci",
    czech: "Žák",
  },
  {
    default: "Plot",
    english: "Plot",
    turkish: "Komplo",
    czech: "Spiknutí",
  },
  {
    default: "Lion",
    english: "Lion",
    turkish: "Aslan",
    czech: "Lev",
  },
  {
    default: "Police",
    english: "Police",
    turkish: "Polis",
    czech: "Policie",
  },
  {
    default: "Head",
    english: "Head",
    turkish: "Kafa",
    czech: "Hlava",
  },
  {
    default: "Litter",
    english: "Litter",
    turkish: "Çöp",
    czech: "Smetí",
  },
  {
    default: "Concert",
    english: "Concert",
    turkish: "Konser",
    czech: "Koncert",
  },
  {
    default: "Mug",
    english: "Mug",
    turkish: "Soygun",
    czech: "Džbánek",
  },
  {
    default: "Vacuum",
    english: "Vacuum",
    turkish: "Vakum",
    czech: "Vakuum",
  },
  {
    default: "Atlantis",
    english: "Atlantis",
    turkish: "Atlantis",
    czech: "Atlantis",
  },
  {
    default: "Straw",
    english: "Straw",
    turkish: "Pipet",
    czech: "Sláma",
  },
  {
    default: "Switch",
    english: "Switch",
    turkish: "Anahtar",
    czech: "Přepínač",
  },
  {
    default: "Skyscraper",
    english: "Skyscraper",
    turkish: "Gökdelen",
    czech: "Mrakodrap",
  },
  {
    default: "Laser",
    english: "Laser",
    turkish: "Lazer",
    czech: "Laser",
  },
  {
    default: "Scuba Diver",
    english: "Scuba Diver",
    turkish: "Tüplü dalış",
    czech: "Potápěč",
  },
  {
    default: "Africa",
    english: "Africa",
    turkish: "Afrika",
    czech: "Afrika",
  },
  {
    default: "Plastic",
    english: "Plastic",
    turkish: "Plastik",
    czech: "Plastický",
  },
  {
    default: "Dwarf",
    english: "Dwarf",
    turkish: "Cüce",
    czech: "Trpaslík",
  },
  {
    default: "Lap",
    english: "Lap",
    turkish: "Kucak",
    czech: "Klín",
  },
  {
    default: "Life",
    english: "Life",
    turkish: "Hayat",
    czech: "Život",
  },
  {
    default: "Honey",
    english: "Honey",
    turkish: "Bal",
    czech: "Miláček",
  },
  {
    default: "Horseshoe",
    english: "Horseshoe",
    turkish: "At nalı",
    czech: "Podkova",
  },
  {
    default: "Unicorn",
    english: "Unicorn",
    turkish: "Tek boynuzlu at",
    czech: "Jednorožec",
  },
  {
    default: "Spy",
    english: "Spy",
    turkish: "Casus",
    czech: "Vyzvědač",
  },
  {
    default: "Pants",
    english: "Pants",
    turkish: "Pantolon",
    czech: "Kalhoty",
  },
  {
    default: "Wall",
    english: "Wall",
    turkish: "Duvar",
    czech: "Zeď",
  },
  {
    default: "Paper",
    english: "Paper",
    turkish: "Kağıt",
    czech: "Papír",
  },
  {
    default: "Sound",
    english: "Sound",
    turkish: "Ses",
    czech: "Zvuk",
  },
  {
    default: "Ice",
    english: "Ice",
    turkish: "Buz",
    czech: "Led",
  },
  {
    default: "Tag",
    english: "Tag",
    turkish: "Etiket",
    czech: "Štítek",
  },
  {
    default: "Web",
    english: "Web",
    turkish: "Ağ",
    czech: "Web",
  },
  {
    default: "Fan",
    english: "Fan",
    turkish: "Fan",
    czech: "Fanoušek",
  },
  {
    default: "Orange",
    english: "Orange",
    turkish: "Turuncu",
    czech: "Oranžový",
  },
  {
    default: "Temple",
    english: "Temple",
    turkish: "Tapınak",
    czech: "Chrám",
  },
  {
    default: "Canada",
    english: "Canada",
    turkish: "Kanada",
    czech: "Kanada",
  },
  {
    default: "Scorpion",
    english: "Scorpion",
    turkish: "Akrep",
    czech: "Štír",
  },
  {
    default: "Undertaker",
    english: "Undertaker",
    turkish: "Cenazeci",
    czech: "Hrobař",
  },
  {
    default: "Mail",
    english: "Mail",
    turkish: "Posta",
    czech: "Pošta",
  },
  {
    default: "Europe",
    english: "Europe",
    turkish: "Avrupa",
    czech: "Evropa",
  },
  {
    default: "Soul",
    english: "Soul",
    turkish: "Ruh",
    czech: "Duše",
  },
  {
    default: "Apple",
    english: "Apple",
    turkish: "Elma",
    czech: "Jablko",
  },
  {
    default: "Pole",
    english: "Pole",
    turkish: "Kutup",
    czech: "Pól",
  },
  {
    default: "Tap",
    english: "Tap",
    turkish: "Musluk",
    czech: "Kohoutek",
  },
  {
    default: "Mouth",
    english: "Mouth",
    turkish: "Ağız",
    czech: "Pusa",
  },
  {
    default: "Ambulance",
    english: "Ambulance",
    turkish: "Ambulans",
    czech: "Záchranář",
  },
  {
    default: "Dress",
    english: "Dress",
    turkish: "Elbise",
    czech: "Šaty",
  },
  {
    default: "Ice Cream",
    english: "Ice Cream",
    turkish: "Dondurma",
    czech: "Zmrzlina",
  },
  {
    default: "Rabbit",
    english: "Rabbit",
    turkish: "Tavşan",
    czech: "Králičí",
  },
  {
    default: "Buck",
    english: "Buck",
    turkish: "Dolar",
    czech: "Dolar",
  },
  {
    default: "Agent",
    english: "Agent",
    turkish: "Ajan",
    czech: "Agent",
  },
  {
    default: "Sock",
    english: "Sock",
    turkish: "Çorap",
    czech: "Ponožka",
  },
  {
    default: "Nut",
    english: "Nut",
    turkish: "Ceviz",
    czech: "Matka",
  },
  {
    default: "Boot",
    english: "Boot",
    turkish: "Bot",
    czech: "Boot",
  },
  {
    default: "Ghost",
    english: "Ghost",
    turkish: "Hayalet",
    czech: "Duch",
  },
  {
    default: "Oil",
    english: "Oil",
    turkish: "Yağ",
    czech: "Olej",
  },
  {
    default: "Superhero",
    english: "Superhero",
    turkish: "Süper kahraman",
    czech: "Superhrdina",
  },
  {
    default: "Code",
    english: "Code",
    turkish: "Kod",
    czech: "Kód",
  },
  {
    default: "Kiwi",
    english: "Kiwi",
    turkish: "Kivi",
    czech: "Kiwi",
  },
  {
    default: "Hospital",
    english: "Hospital",
    turkish: "Hastane",
    czech: "Nemocnice",
  },
  {
    default: "Saturn",
    english: "Saturn",
    turkish: "Satürn",
    czech: "Saturn",
  },
  {
    default: "Film",
    english: "Film",
    turkish: "Film",
    czech: "Film",
  },
  {
    default: "Button",
    english: "Button",
    turkish: "Düğme",
    czech: "Tlačítko",
  },
  {
    default: "Snowman",
    english: "Snowman",
    turkish: "Kardan adam",
    czech: "Sněhulák",
  },
  {
    default: "Helicopter",
    english: "Helicopter",
    turkish: "Helikopter",
    czech: "Helikoptéra",
  },
  {
    default: "Loch Ness",
    english: "Loch Ness",
    turkish: "Loch Ness",
    czech: "Loch Ness",
  },
  {
    default: "Log",
    english: "Log",
    turkish: "Kayıt",
    czech: "Log",
  },
  {
    default: "Princess",
    english: "Princess",
    turkish: "Prenses",
    czech: "Princezna",
  },
  {
    default: "Time",
    english: "Time",
    turkish: "Zaman",
    czech: "Čas",
  },
  {
    default: "Cook",
    english: "Cook",
    turkish: "Aşçı",
    czech: "Kuchař",
  },
  {
    default: "Revolution",
    english: "Revolution",
    turkish: "Devrim",
    czech: "Revoluce",
  },
  {
    default: "Shoe",
    english: "Shoe",
    turkish: "Ayakkabı",
    czech: "Boty",
  },
  {
    default: "Mole",
    english: "Mole",
    turkish: "Köstebek",
    czech: "Krtek",
  },
  {
    default: "Spell",
    english: "Spell",
    turkish: "Hecelemek",
    czech: "Hláskovat",
  },
  {
    default: "Grass",
    english: "Grass",
    turkish: "Çimen",
    czech: "Tráva",
  },
  {
    default: "Washer",
    english: "Washer",
    turkish: "Çamaşır makinesi",
    czech: "Pračka",
  },
  {
    default: "Game",
    english: "Game",
    turkish: "Oyun",
    czech: "Hra",
  },
  {
    default: "Beat",
    english: "Beat",
    turkish: "Vurmak",
    czech: "Porazit",
  },
  {
    default: "Hole",
    english: "Hole",
    turkish: "Delik",
    czech: "Otvor",
  },
  {
    default: "Horse",
    english: "Horse",
    turkish: "At",
    czech: "Kůň",
  },
  {
    default: "Pirate",
    english: "Pirate",
    turkish: "Korsan",
    czech: "Pirát",
  },
  {
    default: "Link",
    english: "Link",
    turkish: "Bağlantı",
    czech: "Odkaz",
  },
  {
    default: "Dance",
    english: "Dance",
    turkish: "Dans",
    czech: "Tanec",
  },
  {
    default: "Fly",
    english: "Fly",
    turkish: "Uçmak",
    czech: "Létat",
  },
  {
    default: "Pit",
    english: "Pit",
    turkish: "Çukur",
    czech: "Jáma",
  },
  {
    default: "Server",
    english: "Server",
    turkish: "Sunucu",
    czech: "Server",
  },
  {
    default: "School",
    english: "School",
    turkish: "Okul",
    czech: "Škola",
  },
  {
    default: "Lock",
    english: "Lock",
    turkish: "Kilit",
    czech: "Zámek",
  },
  {
    default: "Brush",
    english: "Brush",
    turkish: "Fırça",
    czech: "Štětec",
  },
  {
    default: "Pool",
    english: "Pool",
    turkish: "Havuz",
    czech: "Bazén",
  },
  {
    default: "Star",
    english: "Star",
    turkish: "Yıldız",
    czech: "Hvězda",
  },
  {
    default: "Jam",
    english: "Jam",
    turkish: "Reçel",
    czech: "Džem",
  },
  {
    default: "Organ",
    english: "Organ",
    turkish: "Organ",
    czech: "Orgán",
  },
  {
    default: "Berlin",
    english: "Berlin",
    turkish: "Berlin",
    czech: "Berlín",
  },
  {
    default: "Face",
    english: "Face",
    turkish: "Yüz",
    czech: "Tvář",
  },
  {
    default: "Luck",
    english: "Luck",
    turkish: "Şans",
    czech: "Štěstí",
  },
  {
    default: "Amazon",
    english: "Amazon",
    turkish: "Amazon",
    czech: "Amazonka",
  },
  {
    default: "Cast",
    english: "Cast",
    turkish: "Döküm",
    czech: "Sádra",
  },
  {
    default: "Gas",
    english: "Gas",
    turkish: "Gaz",
    czech: "Plyn",
  },
  {
    default: "Club",
    english: "Club",
    turkish: "Kulüp",
    czech: "Klub",
  },
  {
    default: "Sink",
    english: "Sink",
    turkish: "Lavabo",
    czech: "Dřez",
  },
  {
    default: "Water",
    english: "Water",
    turkish: "Su",
    czech: "Voda",
  },
  {
    default: "Chair",
    english: "Chair",
    turkish: "Sandalye",
    czech: "Židle",
  },
  {
    default: "Shark",
    english: "Shark",
    turkish: "Köpek balığı",
    czech: "Žralok",
  },
  {
    default: "Jupiter",
    english: "Jupiter",
    turkish: "Jüpiter",
    czech: "Jupiter",
  },
  {
    default: "Copper",
    english: "Copper",
    turkish: "Bakır",
    czech: "Měď",
  },
  {
    default: "Jack",
    english: "Jack",
    turkish: "Jack",
    czech: "Zvedák",
  },
  {
    default: "Platypus",
    english: "Platypus",
    turkish: "Ornitorenk",
    czech: "Ptakopysk",
  },
  {
    default: "Stick",
    english: "Stick",
    turkish: "Sopa",
    czech: "Lepit",
  },
  {
    default: "Olive",
    english: "Olive",
    turkish: "Zeytin",
    czech: "Olivový",
  },
  {
    default: "Grace",
    english: "Grace",
    turkish: "Lütuf",
    czech: "Milost",
  },
  {
    default: "Bear",
    english: "Bear",
    turkish: "Ayı",
    czech: "Medvěd",
  },
  {
    default: "Glass",
    english: "Glass",
    turkish: "Bardak",
    czech: "Sklenka",
  },
  {
    default: "Row",
    english: "Row",
    turkish: "Sıra",
    czech: "Řádek",
  },
  {
    default: "Pistol",
    english: "Pistol",
    turkish: "Tabanca",
    czech: "Pistole",
  },
  {
    default: "London",
    english: "London",
    turkish: "Londra",
    czech: "Londýn",
  },
  {
    default: "Rock",
    english: "Rock",
    turkish: "Kaynak",
    czech: "Skála",
  },
  {
    default: "Van",
    english: "Van",
    turkish: "Kamyonet",
    czech: "Dodávka",
  },
  {
    default: "Vet",
    english: "Vet",
    turkish: "Veteriner",
    czech: "Vet",
  },
  {
    default: "Beach",
    english: "Beach",
    turkish: "Sahil",
    czech: "Pláž",
  },
  {
    default: "Charge",
    english: "Charge",
    turkish: "Şarj",
    czech: "Nabít",
  },
  {
    default: "Port",
    english: "Port",
    turkish: "Liman",
    czech: "Přístav",
  },
  {
    default: "Disease",
    english: "Disease",
    turkish: "Hastalık",
    czech: "Choroba",
  },
  {
    default: "Palm",
    english: "Palm",
    turkish: "Avuç",
    czech: "Dlaň",
  },
  {
    default: "Moscow",
    english: "Moscow",
    turkish: "Moskova",
    czech: "Moskva",
  },
  {
    default: "Pin",
    english: "Pin",
    turkish: "Toplu iğne",
    czech: "Kolík",
  },
  {
    default: "Washington",
    english: "Washington",
    turkish: "Washington",
    czech: "Washington",
  },
  {
    default: "Pyramid",
    english: "Pyramid",
    turkish: "Piramit",
    czech: "Pyramida",
  },
  {
    default: "Opera",
    english: "Opera",
    turkish: "Opera",
    czech: "Opera",
  },
  {
    default: "Casino",
    english: "Casino",
    turkish: "Kumarhane",
    czech: "Kasino",
  },
  {
    default: "Pilot",
    english: "Pilot",
    turkish: "Pilot",
    czech: "Pilot",
  },
  {
    default: "String",
    english: "String",
    turkish: "Yay",
    czech: "Struna",
  },
  {
    default: "Night",
    english: "Night",
    turkish: "Gece",
    czech: "Noc",
  },
  {
    default: "Chest",
    english: "Chest",
    turkish: "Göğüs",
    czech: "Hruď",
  },
  {
    default: "Yard",
    english: "Yard",
    turkish: "Bahçe",
    czech: "Yard",
  },
  {
    default: "Teacher",
    english: "Teacher",
    turkish: "Öğretmen",
    czech: "Učitel",
  },
  {
    default: "Pumpkin",
    english: "Pumpkin",
    turkish: "Kabak",
    czech: "Dýně",
  },
  {
    default: "Thief",
    english: "Thief",
    turkish: "Hırsız",
    czech: "Zloděj",
  },
  {
    default: "Bark",
    english: "Bark",
    turkish: "Kabuk",
    czech: "Kůra",
  },
  {
    default: "Bug",
    english: "Bug",
    turkish: "Böcek",
    czech: "Brouk",
  },
  {
    default: "Mint",
    english: "Mint",
    turkish: "Nane",
    czech: "Máta",
  },
  {
    default: "Cycle",
    english: "Cycle",
    turkish: "Döngü",
    czech: "Cyklus",
  },
  {
    default: "Telescope",
    english: "Telescope",
    turkish: "Teleskop",
    czech: "Dalekohled",
  },
  {
    default: "Calf",
    english: "Calf",
    turkish: "Buzağı",
    czech: "Tele",
  },
  {
    default: "Air",
    english: "Air",
    turkish: "Hava",
    czech: "Vzduch",
  },
  {
    default: "Box",
    english: "Box",
    turkish: "Kutu",
    czech: "Krabice",
  },
  {
    default: "Mount",
    english: "Mount",
    turkish: "Dağ",
    czech: "Hora",
  },
  {
    default: "Thumb",
    english: "Thumb",
    turkish: "Baş parmak",
    czech: "Palec",
  },
  {
    default: "Antarctica",
    english: "Antarctica",
    turkish: "Antarktika",
    czech: "Antarktida",
  },
  {
    default: "Trunk",
    english: "Trunk",
    turkish: "Gövde",
    czech: "Kmen",
  },
  {
    default: "Snow",
    english: "Snow",
    turkish: "Kar",
    czech: "Sníh",
  },
  {
    default: "Penguin",
    english: "Penguin",
    turkish: "Penguen",
    czech: "Tučňák",
  },
  {
    default: "Root",
    english: "Root",
    turkish: "Kök",
    czech: "Kořen",
  },
  {
    default: "Bar",
    english: "Bar",
    turkish: "Çubuk",
    czech: "Bar",
  },
  {
    default: "File",
    english: "File",
    turkish: "Dosya",
    czech: "Soubor",
  },
  {
    default: "Hawk",
    english: "Hawk",
    turkish: "Şahin",
    czech: "Jestřáb",
  },
  {
    default: "Battery",
    english: "Battery",
    turkish: "Pil",
    czech: "Baterie",
  },
  {
    default: "Slug",
    english: "Slug",
    turkish: "Sümüklüböcek",
    czech: "Slimák",
  },
  {
    default: "Octopus",
    english: "Octopus",
    turkish: "Ahtapot",
    czech: "Chobotnice",
  },
  {
    default: "Whip",
    english: "Whip",
    turkish: "Kırbaç",
    czech: "Bič",
  },
  {
    default: "America",
    english: "America",
    turkish: "Amerika",
    czech: "Amerika",
  },
  {
    default: "Ivory",
    english: "Ivory",
    turkish: "Fildişi",
    czech: "Slonovina",
  },
  {
    default: "Pound",
    english: "Pound",
    turkish: "Pound",
    czech: "Libra",
  },
  {
    default: "Sub",
    english: "Sub",
    turkish: "Denizaltı",
    czech: "Ponorka",
  },
  {
    default: "Cliff",
    english: "Cliff",
    turkish: "Uçurum",
    czech: "Útes",
  },
  {
    default: "Lab",
    english: "Lab",
    turkish: "Laboratuvar",
    czech: "Laboratoř",
  },
  {
    default: "Eagle",
    english: "Eagle",
    turkish: "Kartal",
    czech: "Orel",
  },
  {
    default: "Genius",
    english: "Genius",
    turkish: "Dahi",
    czech: "Génius",
  },
  {
    default: "Ship",
    english: "Ship",
    turkish: "Gemi",
    czech: "Loď",
  },
  {
    default: "Dice",
    english: "Dice",
    turkish: "Zar",
    czech: "Kostky",
  },
  {
    default: "Hood",
    english: "Hood",
    turkish: "Kapüşon",
    czech: "Kapuce",
  },
  {
    default: "Heart",
    english: "Heart",
    turkish: "Kalp",
    czech: "Srdce",
  },
  {
    default: "Novel",
    english: "Novel",
    turkish: "Roman",
    czech: "Román",
  },
  {
    default: "Pipe",
    english: "Pipe",
    turkish: "Boru",
    czech: "Trubka",
  },
  {
    default: "Himalayas",
    english: "Himalayas",
    turkish: "Himalayalar",
    czech: "Himaláje",
  },
  {
    default: "Crown",
    english: "Crown",
    turkish: "Taç",
    czech: "Koruna",
  },
  {
    default: "Round",
    english: "Round",
    turkish: "Yuvarlak",
    czech: "Kolo",
  },
  {
    default: "India",
    english: "India",
    turkish: "Hindistan",
    czech: "Indie",
  },
  {
    default: "Needle",
    english: "Needle",
    turkish: "İğne",
    czech: "Jehla",
  },
  {
    default: "Shop",
    english: "Shop",
    turkish: "Mağaza",
    czech: "Prodejna",
  },
  {
    default: "Watch",
    english: "Watch",
    turkish: "Saat",
    czech: "Hodiny",
  },
  {
    default: "Lead",
    english: "Lead",
    turkish: "Yol göstermek",
    czech: "Vést",
  },
  {
    default: "Tie",
    english: "Tie",
    turkish: "Bağlamak",
    czech: "Kravata",
  },
  {
    default: "Table",
    english: "Table",
    turkish: "Masa",
    czech: "Stůl",
  },
  {
    default: "Cell",
    english: "Cell",
    turkish: "Hücre",
    czech: "Buňka",
  },
  {
    default: "Cover",
    english: "Cover",
    turkish: "Kapak",
    czech: "Pokrýt",
  },
  {
    default: "Czech",
    english: "Czech",
    turkish: "Çek",
    czech: "Čeština",
  },
  {
    default: "Back",
    english: "Back",
    turkish: "Geri",
    czech: "Zadní",
  },
  {
    default: "Bomb",
    english: "Bomb",
    turkish: "Bomba",
    czech: "Bomba",
  },
  {
    default: "Ruler",
    english: "Ruler",
    turkish: "Cetvel",
    czech: "Pravítko",
  },
  {
    default: "Forest",
    english: "Forest",
    turkish: "Orman",
    czech: "Les",
  },
  {
    default: "Bottle",
    english: "Bottle",
    turkish: "Şişe",
    czech: "Láhev",
  },
  {
    default: "Space",
    english: "Space",
    turkish: "Uzay",
    czech: "Vesmír",
  },
  {
    default: "Hook",
    english: "Hook",
    turkish: "Kanca",
    czech: "Háček",
  },
  {
    default: "Doctor",
    english: "Doctor",
    turkish: "Doktor",
    czech: "Doktor",
  },
  {
    default: "Ball",
    english: "Ball",
    turkish: "Top",
    czech: "Míč",
  },
  {
    default: "Bow",
    english: "Bow",
    turkish: "Yay",
    czech: "Luk",
  },
  {
    default: "Degree",
    english: "Degree",
    turkish: "Derece",
    czech: "Stupeň",
  },
  {
    default: "Rome",
    english: "Rome",
    turkish: "Roma",
    czech: "Řím",
  },
  {
    default: "Plane",
    english: "Plane",
    turkish: "Uçak",
    czech: "Letadlo",
  },
  {
    default: "Giant",
    english: "Giant",
    turkish: "Devasa",
    czech: "Obří",
  },
  {
    default: "Nail",
    english: "Nail",
    turkish: "Tırnak",
    czech: "Nehet",
  },
  {
    default: "Dragon",
    english: "Dragon",
    turkish: "Ejderha",
    czech: "Drak",
  },
  {
    default: "Stadium",
    english: "Stadium",
    turkish: "Stadyum",
    czech: "Stadión",
  },
  {
    default: "Flute",
    english: "Flute",
    turkish: "Flüt",
    czech: "Flétna",
  },
  {
    default: "Carrot",
    english: "Carrot",
    turkish: "Havuç",
    czech: "Mrkev",
  },
  {
    default: "Wake",
    english: "Wake",
    turkish: "Uyanmak",
    czech: "Probudit",
  },
  {
    default: "Fighter",
    english: "Fighter",
    turkish: "Savaşçı",
    czech: "Bojovník",
  },
  {
    default: "Model",
    english: "Model",
    turkish: "Model",
    czech: "Modelka",
  },
  {
    default: "Tokyo",
    english: "Tokyo",
    turkish: "Tokyo",
    czech: "Tokio",
  },
  {
    default: "Eye",
    english: "Eye",
    turkish: "Göz",
    czech: "Oko",
  },
  {
    default: "Mexico",
    english: "Mexico",
    turkish: "Meksika",
    czech: "Mexiko",
  },
  {
    default: "Hand",
    english: "Hand",
    turkish: "El",
    czech: "Ruka",
  },
  {
    default: "Swing",
    english: "Swing",
    turkish: "Salıncak",
    czech: "Houpačka",
  },
  {
    default: "Key",
    english: "Key",
    turkish: "Anahtar",
    czech: "Klíč",
  },
  {
    default: "Alien",
    english: "Alien",
    turkish: "Yabancı",
    czech: "Mimozemšťan",
  },
  {
    default: "Tower",
    english: "Tower",
    turkish: "Kule",
    czech: "Věž",
  },
  {
    default: "Poison",
    english: "Poison",
    turkish: "Zehir",
    czech: "Jed",
  },
  {
    default: "Cricket",
    english: "Cricket",
    turkish: "Kriket",
    czech: "Kriket",
  },
  {
    default: "Cold",
    english: "Cold",
    turkish: "Soğuk",
    czech: "Studený",
  },
  {
    default: "Knife",
    english: "Knife",
    turkish: "Bıçak",
    czech: "Nůž",
  },
  {
    default: "Church",
    english: "Church",
    turkish: "Kilise",
    czech: "Kostel",
  },
  {
    default: "Board",
    english: "Board",
    turkish: "Pano",
    czech: "Prkno",
  },
  {
    default: "Cloak",
    english: "Cloak",
    turkish: "Pelerin",
    czech: "Plášť",
  },
  {
    default: "Ninja",
    english: "Ninja",
    turkish: "Ninja",
    czech: "Ninja",
  },
  {
    default: "Olympus",
    english: "Olympus",
    turkish: "Olimpos",
    czech: "Olympus",
  },
  {
    default: "Belt",
    english: "Belt",
    turkish: "Kemer",
    czech: "Pás",
  },
  {
    default: "Light",
    english: "Light",
    turkish: "Işık",
    czech: "Světlo",
  },
  {
    default: "Death",
    english: "Death",
    turkish: "Ölüm",
    czech: "Smrt",
  },
  {
    default: "Stock",
    english: "Stock",
    turkish: "Stoklamak",
    czech: "Sklad",
  },
  {
    default: "Millionaire",
    english: "Millionaire",
    turkish: "Milyoner",
    czech: "Milionář",
  },
  {
    default: "Day",
    english: "Day",
    turkish: "Gün",
    czech: "Den",
  },
  {
    default: "Knight",
    english: "Knight",
    turkish: "Şövalye",
    czech: "Rytíř",
  },
  {
    default: "Pie",
    english: "Pie",
    turkish: "Turta",
    czech: "Koláč",
  },
  {
    default: "Bed",
    english: "Bed",
    turkish: "Yatak",
    czech: "Postel",
  },
  {
    default: "Circle",
    english: "Circle",
    turkish: "Daire",
    czech: "Kruh",
  },
  {
    default: "Rose",
    english: "Rose",
    turkish: "Gül",
    czech: "Růže",
  },
  {
    default: "Change",
    english: "Change",
    turkish: "Değişim",
    czech: "Změna",
  },
  {
    default: "Cap",
    english: "Cap",
    turkish: "Kapak",
    czech: "Víčko",
  },
  {
    default: "Triangle",
    english: "Triangle",
    turkish: "Üçgen",
    czech: "Trojúhelník",
  },
];
